### ISSUE TITLE
European version also uses digits+letters in the bootloader unlock code

### ISSUE THREAD

**Issue by michal25** [programminghoch10/huawei-honor-bootloader-bruteforce#6]
I have two Huawei Honor 6a models and both had digits+letters in the bootloader unlock code.
Both are european version.
Can you update this excellent script, please? I need to unlock Huawei P10 Lite and Octoplus Box is not working for this model :-(

Best regards
Michal

**Comment by programminghoch10** [comment]
https://github.com/SkyEmie/huawei-honor-unlock-bootloader/issues/54
Did so already...
But beware: This script is not a magic solution to unlocking all devices. It might work, but it most likely won't.
