### ISSUE TITLE
          FAILED (Status read failed (Too many links)) fastboot: error: Command failed  

### ISSUE THREAD

**Issue by KikoPlays44** [programminghoch10/huawei-honor-bootloader-bruteforce#9]
So. I am getting this error when I am in10.04% of progress. it gives me this error: 
Bruteforce is running...
Currently testing code 1003762494701500
Progress: 10.04%
                                                   FAILED (Status read failed (Too many links))
fastboot: error: Command failed

Bruteforce is running...
Currently testing code 1003792594659112
Progress: 10.04%
and then the phone reboots to the battery symbol. and stays stuck there.

**Comment by KikoPlays44** [comment]
so. I  managed to skip the problem by changing the  algoOEMcode variable. I am going to leave it overnight and opfully tomorrow it will be done. I hope....

**Comment by programminghoch10** [comment]
Is your battery charged?
Please charge it completely before trying, even though connected, the phone might not be charging in Fastboot mode.

**Comment by KikoPlays44** [comment]
> Is your battery charged?
> Please charge it completely before trying, even though connected, the phone might not be charging in Fastboot mode.

Got it. The phone's battery life sucks. Sorry for only replying now.
